/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RosaryRouteImport } from './routes/rosary'
import { Route as ReadingsRouteImport } from './routes/readings'
import { Route as PrayersRouteImport } from './routes/prayers'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrayerIdRouteImport } from './routes/prayer.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RosaryRoute = RosaryRouteImport.update({
  id: '/rosary',
  path: '/rosary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingsRoute = ReadingsRouteImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayersRoute = PrayersRouteImport.update({
  id: '/prayers',
  path: '/prayers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerIdRoute = PrayerIdRouteImport.update({
  id: '/prayer/$id',
  path: '/prayer/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/prayers': typeof PrayersRoute
  '/readings': typeof ReadingsRoute
  '/rosary': typeof RosaryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/prayer/$id': typeof PrayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/prayers': typeof PrayersRoute
  '/readings': typeof ReadingsRoute
  '/rosary': typeof RosaryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/prayer/$id': typeof PrayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/prayers': typeof PrayersRoute
  '/readings': typeof ReadingsRoute
  '/rosary': typeof RosaryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/prayer/$id': typeof PrayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/prayers'
    | '/readings'
    | '/rosary'
    | '/sitemap.xml'
    | '/prayer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/prayers'
    | '/readings'
    | '/rosary'
    | '/sitemap.xml'
    | '/prayer/$id'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/prayers'
    | '/readings'
    | '/rosary'
    | '/sitemap.xml'
    | '/prayer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  PrayersRoute: typeof PrayersRoute
  ReadingsRoute: typeof ReadingsRoute
  RosaryRoute: typeof RosaryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PrayerIdRoute: typeof PrayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rosary': {
      id: '/rosary'
      path: '/rosary'
      fullPath: '/rosary'
      preLoaderRoute: typeof RosaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readings': {
      id: '/readings'
      path: '/readings'
      fullPath: '/readings'
      preLoaderRoute: typeof ReadingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayers': {
      id: '/prayers'
      path: '/prayers'
      fullPath: '/prayers'
      preLoaderRoute: typeof PrayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer/$id': {
      id: '/prayer/$id'
      path: '/prayer/$id'
      fullPath: '/prayer/$id'
      preLoaderRoute: typeof PrayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  PrayersRoute: PrayersRoute,
  ReadingsRoute: ReadingsRoute,
  RosaryRoute: RosaryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PrayerIdRoute: PrayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
